### ISSUE TITLE
error since last update 

### ISSUE THREAD

**Issue by PhilippeBach** [aliomattux/mage2odoo#5]
all task import are ok except orders with this error

Odoo

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/aliomattux/mage2odoo/models/job.py", line 26, in button_execute_job
    result = self.import_resources(cr, uid, job)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/aliomattux/mage2odoo/models/job.py", line 42, in import_resources
    return getattr(job_obj, job.python_function_name)(cr, uid, job)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/aliomattux/mage2odoo/jobs/sale.py", line 24, in import_sales_orders
    self.import_one_storeview_orders(cr, uid, job, storeview, defaults, mappinglines)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/aliomattux/mage2odoo/jobs/sale.py", line 69, in import_one_storeview_orders
    order_data = self._get_job_data(cr, uid, job, 'sales_order.list', [filters])
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/aliomattux/mage2odoo/models/mage_api.py", line 30, in _get_job_data
    return self._mage_call(credentials, method, arguments)
  File "/opt/odoo/aliomattux/mage2odoo/models/mage_api.py", line 39, in _mage_call
    return mage_api.call(method, arguments)
  File "/usr/local/lib/python2.7/dist-packages/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 557, in feed
    self._parser.Parse(data, 0)
ExpatError: syntax error: line 2, column 0

i have this error since the last update 

Philippe

**Comment by PhilippeBach** [comment]
after increasing ithe php max_mem parameter from 256 to 1024 everything is ok
