### ISSUE TITLE
Invalid api path

### ISSUE THREAD

**Issue by alejo9109** [aliomattux/mage2odoo#8]
hello im use this module in my proyect but i need a some manual for config magento setup because i recive this error

Magento Returned an Error Fault 3: 'Invalid api path.

I use SOAP/XML-RPC user and SOAP/XML-RPC role please how config magento and odoo

**Comment by aliomattux** [comment]
This error means that you did not install the Magento module correctly

The Openobject folder needs to go in app/code/local and the module xml
needs to go in app/etc/modules. If you do not know how to do this, I
suggest you review how to install a Magento module. You also need to create
a webservices user with full permissions

**Comment by alejo9109** [comment]
thanks at least the error no longer appears, but when I try to export a product odoo to Magento that appears this

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
AttributeError: 'mage.export.wizard' object has no attribute 'export_products'

**Comment by aliomattux** [comment]
I do not support currently the export product functionality

**Comment by alejo9109** [comment]
and another tool that you recommend?
